version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-oop
    ports:
      - '8090:80'
    volumes:
      - .:/var/www/html
      - ./docker/site.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
    container_name: php-oop
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql-oop
    restart: always
    ports:
      - '3001:3306'
    environment:
      MYSQL_ROOT_PASSWORD: oop
      MYSQL_DATABASE: oop
      MYSQL_USER: oop
      MYSQL_PASSWORD: oop
    volumes:
      - /var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d

